baseurl = "https://derailed-dash.github.io/demo-lz-docs"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Demo GCP LZ Docs"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "Learn"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Demo Docs Site to Support a Generic GCP Landing Zone"
  logo = "src/static/images/logo.jpeg"
  favicon = "src/static/images/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "Darren Lester"
  email = "darren_lester@epam.com"
  gitlab = "username"
  github = "darren-lester-epam"
  linkedin = "username"
